language: generic
sudo: true
os:
  - linux
  - osx
env:
  - RUST_BACKTRACE=1 


install:
  - yes | ./scripts/dev_setup.sh
  
before_script:
  - source $HOME/.cargo/env
script:
  - cargo build -j 16 --all --all-targets
  - cargo test --all --exclude testsuite
  - cargo test --package testsuite
